### ISSUE TITLE
Website for better understanding of this project to users

### ISSUE THREAD

**Issue by roxoho** [prajwalkulkarni/take-a-break#2]
**Is your feature request related to a problem? Please describe.**
Hi, I am thinking that a website describing this project would be amazing as the users can get better understanding through the website.

**Describe the solution you'd like**
A simple webpage using React, focusing on images and video examples. Layout would be simple.

**Describe alternatives you've considered**

**Additional context**

**Comment by prajwalkulkarni** [comment]
Hello @roxoho 
Thank you for thinking through this. However, at this point, I believe the single purpose of this extension is simple and a brief explanation on the Chrome Web store would be sufficient to help users understand the application of this extension. 

If there are any other contributions you can think of, please feel free to write them here. 

Regards,
Prajwal

**Comment by roxoho** [comment]
Ok, I understand. I will let you know if some idea comes to my mind.
Thanks
